apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkite-agent-builder-private-git
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: buildkite-agent-builder-private-git
        heritage: helm
    spec:
      containers:
        - name: buildkite-agent
          image: buildkite/agent:ubuntu-docker
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 400m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            # BUILDKITE AGENT ENV VARS
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-builder-private-token
                  key: token
            - name: BUILDKITE_AGENT_META_DATA
              value: "role=builder-private"
            - name: SSH_PRIVATE_RSA_KEY
              valueFrom:
                secretKeyRef:
                  name: buildkite-agent-builder-ssh-key
                  key: id-rsa
            - name: DIND
              value: "true"
          volumeMounts:
            - name: var-lib-docker
              mountPath: /var/lib/docker
      volumes:
        - name: var-lib-docker
          emptyDir: {}
